### ISSUE TITLE
no case clause matching error

### ISSUE THREAD

**Issue by berayb** [emqx/emqx-bridge-mqtt#112]
Hi, trying to bridge to AWS MQ. MQTTX is able to connect with the following configuration:

host: mqtts:// - xyz.mq.amazonaws.com
port: 8883
SSL: true
Certificate: CA Signed server

Error log: 
no case clause matching ["mqtts",
                                              "//xyz.mq.amazonaws.com",
                                              "8883"]

**Comment by HJianBo** [comment]
Hi @berayb This looks like it should be caused by an incorrect configuration. The `bridge.mqtt.aws.address` option should configured a Domain Name + Port, E.G:
```
bridge.mqtt.aws.address = xyz.mq.amazonaws.com:8883
```

**Comment by berayb** [comment]
> Hi @berayb This looks like it should be caused by an incorrect configuration. The `bridge.mqtt.aws.address` option should configured a Domain Name + Port, E.G:
> 
> ```
> bridge.mqtt.aws.address = xyz.mq.amazonaws.com:8883
> ```

Thanks, @HJianBo, that worked.
