### ISSUE TITLE
Rabbitmq bridge duplicating messages

### ISSUE THREAD

**Issue by radumazi** [emqx/emqx-bridge-mqtt#13]
Hello,
I have a 3 node emqx cluster, with a rabbitmq bridge. At the moment the bridge is configured on all 3 nodes, so when I get a new message on the forwarded topic, I get 3 messages in rabbitmq. Is this normal behaviour? If so, how should I set things up so that I don't loose messages when one node goes down (while also receiving just one copy of each message)?

Thank you,
Radu

**Comment by jerry-chao** [comment]
If you add mqtt bridge on all 3 nodes and bridge the message to rabbitmq, you can try share subscription.  In that case, there are only one subscription which can receive the message @radumazi

**Comment by radumazi** [comment]
Thank you for the response, unfortunately I'm not able to get this to work for bridges. After running
`emqx_ctl bridges add-forward aws "$queue/device/#"` on each node, I still get the same behaviour (3x each message).

**Comment by jerry-chao** [comment]
I have checkout the resource and test it,  and it does not work correctly @radumazi

**Comment by gilbertwong96** [comment]
I'll check it, thanks for your feedback @radumazi .

**Comment by jerry-chao** [comment]
https://github.com/emqx/emqx-bridge-mqtt/blob/e88159e33d5fe0a3eb404a5096a7babf84830bbf/src/emqx_bridge_worker.erl#L604

Maybe add emqx_topic:parse for topic and subopts before emqx_broker:subscribe 
```
{NewTopic, SubOpts} = emqx_topic:parse(Topic, #{qos => ?QOS_1, subid => name()}),
ok = emqx_broker:subscribe(NewTopic, SubOpts).
```

@gilbertwong96

**Comment by gilbertwong96** [comment]
Here is https://github.com/emqx/emqx-bridge-mqtt/pull/18,  anyway, thanks for your suggestion.

**Comment by radumazi** [comment]
When will this fix be included in emqx? I see it's only included under tag v4.0-alpha.1 of the emqx-bridge-mqtt, does this mean it will only be included with emqx v4?
Thank you

**Comment by gilbertwong96** [comment]
Hi, @radumazu, you can just checkout the commit which has been fixed in emqx-bridge-mqtt and build the emqx by yourself.

Gilbert Wong

**Comment by radumazi** [comment]
Thanks for the quick response, i'll try to do that

**Comment by radumazi** [comment]
Hey again, @gilbertwong96 I tried building emqx myself but anything after the fix (tried 3.3, 4.0, master, develop) throws this error when trying to load the plugin (everything stock, I didn't change settings or anyghing, just built the docker image and ran it):
`node.max_ports=1048576                                                                                                                                                                                             
listener.tcp.external.acceptors=64                                                                                                                                                                                 
listener.ssl.external.acceptors=32                                                                                                                                                                                 
node.process_limit=2097152                                                                                                                                                                                         
node.max_ets_tables=2097152                                                                                                                                                                                        
listener.ws.external.acceptors=16                                                                                                                                                                                  
node.name=8dcc4202bac5@172.17.0.2                                                                                                                                                                                  
emqx v3.3-alpha.1 is started successfully!                                                                                                                                                                         
['2019-09-13T08:39:42Z']:emqx start                                                                                                                                                                                
2019-09-13 08:39:54.009 [error] ** State machine emqx_bridge_worker_aws terminating                                                                                                                                
** When server state  = {undefined,undefined}                                                                                                                                                                      
** Reason for termination = error:{'module could not be loaded',replayq}                                                                                                                                           
** Callback mode = undefined                                                                                                                                                                                       
** Stacktrace =                                                                                                                                                                                                    
**  [{emqx_bridge_worker,init,1,                                                                                                                                                                                   
                         [{file,"/emqx_rel/_build/emqx/lib/emqx_bridge_mqtt/src/emqx_bridge_worker.erl"},                                                                                                          
                          {line,282}]},                                                                                                                                                                            
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},                                                                                                                                                  
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]                                                                                                                                              
2019-09-13 08:39:54.011 [error] crasher:                                                                                                                                                                           
    initial call: emqx_bridge_worker:init/1                                                                                                                                                                        
    pid: <0.1857.0>                                                                                                                                                                                                
    registered_name: []
    exception error: undefined function replayq:open/1
      in function  emqx_bridge_worker:init/1 (/emqx_rel/_build/emqx/lib/emqx_bridge_mqtt/src/emqx_bridge_worker.erl, line 282)
      in call from gen_statem:init_it/6 (gen_statem.erl, line 697)
    ancestors: [emqx_bridge_mqtt_sup,<0.1855.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1856.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 40259
  neighbours:
2019-09-13 08:39:54.009 [error] supervisor: {local,emqx_bridge_mqtt_sup}
    errorContext: start_error
    reason: undef
    offender: [{pid,undefined},
              {id,aws},                                                                                                                                                                                           
               {mfargs,                                                                                                                                                                                            
                   {emqx_bridge_worker,start_link,                                                                                                                                                                 
                       [aws,                                                                                                                                                                                       
                        [{address,"127.0.0.1:1883"},                                                                                                                                                               
                         {bridge_mode,true},                                                                                                                                                                       
                         {clean_start,true},                                                                                                                                                                       
                         {client_id,"bridge_aws"},                                                                                                                                                                 
                         {connect_module,emqx_bridge_mqtt},                                                                                                                                                        
                         {forwards,["topic1/#","topic2/#"]},                                                                                                                                                       
                         {keepalive,60000},                                                                                                                                                                        
                         {max_inflight_batches,32},                                                                                                                                                                
                         {mountpoint,"bridge/aws/${node}/"},                                                                                                                                                       
                         {password,"passwd"},                                                                                                                                                                      
                         {proto_ver,v4},                                                                                                                                                                           
                         {queue,                                                                                                                                                                                   
                             #{batch_bytes_limit => 1048576000,                                                                                                                                                    
                               batch_count_limit => 32,                                                                                                                                                            
                               max_total_size => 5368709120,                                                                                                                                                       
                               replayq_dir => "data/emqx_aws_bridge/",
                               replayq_seg_bytes => 10485760}},
                         {reconnect_delay_ms,30000},
                         {retry_interval,20000},
                         {ssl,false},
                         {ssl_opts,
                             [{versions,['tlsv1.2','tlsv1.1',tlsv1]},
                              {ciphers,
                                  [{psk,aes_128_cbc,sha},
                                   {psk,aes_256_cbc,sha},
                                   {psk,'3des_ede_cbc',sha},
                                   {psk,rc4_128,sha}]},
                              {user_lookup_fun,{fun emqx_psk:lookup/3,<<>>}},
                              {keyfile,"etc/certs/client-key.pem"},
                              {ciphers,
                                  ["ECDHE-ECDSA-AES256-GCM-SHA384",
                                   "ECDHE-RSA-AES256-GCM-SHA384"]},
                              {certfile,"etc/certs/client-cert.pem"},
                              {cacertfile,"etc/certs/cacert.pem"}]},
                         {start_type,manual},
                         {subscriptions,[{"cmd/topic1",1},{"cmd/topic2",1}]},
                         {username,"user"}]]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2019-09-13 08:39:54.015 [error] crasher:
    initial call: application_master:init/4
    pid: <0.1854.0>
    registered_name: []
    exception exit: {{shutdown,{failed_to_start_child,aws,undef}},
                     {emqx_bridge_mqtt_app,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.1853.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1855.0>,normal}]
    links: [<0.1853.0>,<0.1255.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:
2019-09-13 08:39:54.015 [error] [Plugins] Load plugin emqx_bridge_mqtt failed, cannot start plugin emqx_bridge_mqtt for {{shutdown,                                                                               
                                                                                          {failed_to_start_child,                                                                                                 
                                                                                           aws,
                                                                                           undef}},
                                                                                         {emqx_bridge_mqtt_app,                                                                                                   
                                                                                          start,
                                                                                          [normal,
                                                                                           []]}}
`

**Comment by gilbertwong96** [comment]
It seems that the dependency replayq has not been built into the docker edition of emqx, maybe you can ask @zhanghongtong for more suggestions.

**Comment by radumazi** [comment]
Hey, thanks for the help @gilbertwong96 . @zhanghongtong any suggestions would be greatly appreciated.

**Comment by radumazi** [comment]
Update:
I tried building emqx 3.2 with an updated version of the bridge_mqtt plugins, and I was able to load the plugin, but couldn't do anything with it. The emqx_ctl bridges list throws errors:
- bridge_mqtt on master branch:
`CMD Error:undef, Stacktrace:[{emqx_ctl,print,
                                    ["name: ~s     status: ~s~n",
                                     [aws,<<"Stopped">>]],
                                    []},
                                   {lists,foreach,2,
                                    [{file,"lists.erl"},{line,1338}]},
                                   {emqx_ctl,run_command,2,
                                    [{file,
                                      "/emqx_rel/_build/emqx/lib/emqx/src/emqx_ctl.erl"},
                                     {line,80}]},
                                   {rpc,'-handle_call_call/6-fun-0-',5,
                                    [{file,"rpc.erl"},{line,197}]}]`
- bridge_mqtt on commit 25dfdad0a0c0b7dcb26283ceeb6d22f4fc331407
`RPC to emqx@10.36.2.4 error: undef`

**Comment by turtleDeng** [comment]
Hi, @radumazi @jerry-chao  Sorry for the late reply, Thank you for your participation, we refactored emqx_bridge_mqtt in emqx4.0, please use the latest version.

**Comment by radumazi** [comment]
@turtleDeng Emqx 4 is out, nice! Thanks for letting me now. I'll check it this week.

**Comment by radumazi** [comment]
@turtleDeng Unfortunately it is still not working properly for me. As before, I tried with this command
`emqx_ctl bridges add-forward aws "$queue/device/#"` and with a 2 node and 3 node cluster, just to make sure there's not an issue with rabbit. The results are quite clear: I publish 10 messages on emqx, and if I have 2 nodes, I get 20 messages in rabbit, if I have 3 nodes, I get 30 messages in rabbit.
Is it working for you? Am I doing something wrong?

**Comment by turtleDeng** [comment]
Carry special $ symbol in shell, please use
```
emqx_ctl bridges add-forward aws '$queue/device/#'
```

**Comment by radumazi** [comment]
Hey, thanks for the help, I confirm it works now.
For anyone having similar issues as I had, a thing to note is that you should publish to device/_id_, not /device/_id_ or it will not work (the difference is the / at the beginning)

**Comment by berayb** [comment]
@turtleDeng Same problem occurs, 

bridge.mqtt.aws.forwards =+,$SYS/brokers/emqx@127.0.0.1/clients/+/connected,$SYS/brokers/emqx@127.0.0.1/clients/+/disconnected

Connected & Disconnected not working, in addition to duplicate problem.

**Comment by turtleDeng** [comment]
@berayb  
Have you modified the node name of emqx? You can choose to subscribe using wildcards
`` `
bridge.mqtt.aws.forwards =+,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected
`` `

**Comment by berayb** [comment]
@turtleDeng Yes, each node is named like emqx@ip. Trying the correct wildcards

**Comment by berayb** [comment]
@turtleDeng Thanks, wildcards worked perfectly. What would you recommend for the duplicate ?

**Comment by turtleDeng** [comment]
Message duplication, please use shared subscription
```
$share/${groupname}/${topic} or '$queue/${topic}
```

**Comment by berayb** [comment]
@turtleDeng Thanks, can I use that for bridge ? For example this one : 

bridge.mqtt.aws.forwards =+,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected

**Comment by berayb** [comment]
@emqplus Is there any chance that you might have a look at this problem ? Thanks.

**Comment by turtleDeng** [comment]
@berayb Yes, you can.

**Comment by berayb** [comment]
> @berayb Yes, you can.

Thanks @turtleDeng , 

I tried like this -> $share/$SYS/brokers/+/clients/+/connected but it did not recognize.

Is it possible to provide an example ? Best,

**Comment by turtleDeng** [comment]
```
$share/${group_id}/$SYS/brokers/+/clients/+/connected
```
https://docs.emqx.io/broker/latest/en/advanced/shared-subscriptions.html

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue, if you have any questions, you can open it.

**Comment by berayb** [comment]
> ```
> bridge.mqtt.aws.forwards =+,$SYS/brokers/+/clients/+/connected,$SYS/brokers/+/clients/+/disconnected
> ```

After upgrading to version 4.1, only connected and disconnected messages arrive. No published data.

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
