### ISSUE TITLE
Start bridge error with bad_action_from_state_function

### ISSUE THREAD

**Issue by MikeSpark** [emqx/emqx-bridge-mqtt#35]
We're on EMQX Broker v3.2.1 trying to setup MQTT bridge to Azure IoT Hub, which accept MQTTv3.1.1; no matter what settings we use, the bridge starts always error with bad_action_from_state_function. 

2019-10-08 00:41:02.560 [error] supervisor: {local,emqx_bridge_mqtt_sup}
    errorContext: child_terminated
    reason: {{bad_action_from_state_function,
                 #{batch_bytes_limit => 1048576000,batch_count_limit => 32,
                   bridge_handler => undefined,
                   connect_fun => #Fun<emqx_bridge_worker.5.75989401>,
                   connect_module => emqx_bridge_mqtt,connection => undefined,
                   forwards => [<<"events/">>],
                   if_record_metrics => true,inflight => [],
                   max_inflight_batches => 32,
                   mountpoint => <<"devices/demodevice/messages/">>,
                   reconnect_delay_ms => 30000,
                   replayq =>
                       #{committer => <0.1318.0>,
                         config =>
                             #{dir => "data/emqx_aws_bridge/",
                               seg_bytes => 10485760},
                         head_segno => 1,
                         in_mem => {[],[]},
                         marshaller => #Fun<emqx_bridge_worker.3.75989401>,
                         sizer => fun emqx_bridge_msg:estimate_size/1,
                         stats => #{bytes => 0,count => 0},
                         w_cur =>
                             #{bytes => 0,count => 0,
                               fd =>
                                   {file_descriptor,raw_file_io_delayed,
                                       #{buffer =>
                                             #Ref<0.3927171588.2328231938.225059>,
                                         delay_size => 65536,
                                         owner => <0.1316.0>,
                                         pid => <0.1317.0>}},
                               segno => 1}},
                   start_type => manual,
                   subscriptions =>
                       [{<<"cmd/topic1">>,1},{<<"cmd/topic2">>,1}]}},
             [{gen_statem,parse_actions_timeout,6,
                  [{file,"gen_statem.erl"},{line,1391}]},
              {gen_statem,loop_event_actions_list,10,
                  [{file,"gen_statem.erl"},{line,1206}]},
              {proc_lib,init_p_do_apply,3,
                  [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1316.0>},
               {id,aws},
               {mfargs,
                   {emqx_bridge_worker,start_link,
                       [aws,
                        [{address,
                             "MightyMikePlayGround.azure-devices.net:1883"},
                         {bridge_mode,true},
                         {clean_start,true},
                         {client_id,"demodevice"},
                         {connect_module,emqx_bridge_mqtt},
                         {forwards,["events/"]},
                         {keepalive,60000},
                         {max_inflight_batches,32},
                         {mountpoint,"devices/demodevice/messages/"},
                         {password,
                             "SharedAccessSignature sr=MightyMikePlayGround.azure-devices.net%2Fdevices%2Fdemodevice&sig=XDqggxx7l4rcDQSn18vQn5JvuSWEGAWJyDV78eRrJhc%3D&se=1606007550"},
                         {proto_ver,v4},
                         {queue,
                             #{batch_bytes_limit => 1048576000,
                               batch_count_limit => 32,
                               replayq_dir => "data/emqx_aws_bridge/",
                               replayq_seg_bytes => 10485760}},
                         {reconnect_delay_ms,30000},
                         {retry_interval,20000},
                         {ssl,true},
                         {ssl_opts,
                             [{versions,['tlsv1.2','tlsv1.1',tlsv1]},
                              {ciphers,
                                  [{psk,aes_128_cbc,sha},
                                   {psk,aes_256_cbc,sha},
                                   {psk,'3des_ede_cbc',sha},
                                   {psk,rc4_128,sha}]},
                              {user_lookup_fun,{fun emqx_psk:lookup/3,<<>>}},
                              {keyfile,"etc/certs/client-key.pem"},
                              {ciphers,
                                  ["ECDHE-ECDSA-AES256-GCM-SHA384",
                                   "ECDHE-RSA-AES256-GCM-SHA384"]},
                              {certfile,"etc/certs/client-cert.pem"},
                              {cacertfile,"etc/certs/cacert.pem"}]},
                         {start_type,manual},
                         {subscriptions,[{"cmd/topic1",1},{"cmd/topic2",1}]},
                         {username,
                             "MightyMikePlayGround.azure-devices.net/demodevice/?api-version=2018-06-30"}]]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in the latest emqx-v4.0-rc.3 version.
