### ISSUE TITLE
Bridge Keepalive Being Multiplied By 1000

### ISSUE THREAD

**Issue by brandonhudson** [emqx/emqx-bridge-mqtt#36]
The bridge keepalive is being multiplied by 1000 based on the configuration settings.

For example, setting:
```
bridge.mqtt.example.keepalive = 300s
```
Results in a keepalive that is `30,000` seconds long (based on the feedback from the EMQX dashboard.

When I set:
```
bridge.mqtt.example.keepalive = 0.3s
```
I get the correct `300` second keepalive interval.

**Comment by brandonhudson** [comment]
Likely stemming from this line:

https://github.com/emqx/emqx-bridge-mqtt/blob/master/src/emqx_bridge_mqtt_actions.erl#L458

It appears to be set to `s` with the cuddlefish parse, where other configuration variables that use seconds  (ex: `retry_interval` - [Referenced Here](https://github.com/emqx/emqx-bridge-mqtt/blob/master/src/emqx_bridge_mqtt_actions.erl#L462)) use `ms` to designate their durations.

This would also explain why it's always 1,000 seconds higher.

**Comment by turtleDeng** [comment]
Thanks for your feedback, we have fixed it in the latest version.
