### ISSUE TITLE
"Start bridge failed." AWS IoT Core

### ISSUE THREAD

**Issue by sgoveia** [emqx/emqx-bridge-mqtt#57]
Hello, attempting to forward to AWS IoT Core, with no success....

**EMQX Version:** Docker v4.0.1

1. Created private key and cert in AWS IoT (1-click), Activated and Attached Policy.
2. Have tried using all rootCA.pem files from here: https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs

3. Downloaded and copied AWS keys and cert files to `/opt/emqx/etc/certs`
4. Started emqx bridge plugin(from emqx UI)
5. Updated `emqx_bridge_mqtt.conf` file.
6. Restarted emqx `/opt/emqx $./bin/emqx restart`

7. `/opt/emqx $ emqx_ctl bridges list`
`name: aws     status: Stopped`

8. `/opt/emqx $ emqx_ctl bridges start aws`
    `Start bridge failed.`

Please, any help would be so appreciated.... I have spent several hours trying to get this to work.. Thank you in advance..!

Below is my `emqx_bridge_mqtt.conf` file.(all other kvp's not shown from emqx_bridge_mqtt.conf have been commented out)

----

`bridge.mqtt.aws.address = a3qeho93ob90uv-ats.iot.us-east-1.amazonaws.com:8883`
`bridge.mqtt.aws.proto_ver = mqttv4`
`bridge.mqtt.aws.start_type = manual`
`bridge.mqtt.aws.bridge_mode = true`
`bridge.mqtt.aws.clientid = bridge_aws`
`bridge.mqtt.aws.clean_start = true`
`bridge.mqtt.aws.username = admin`
`bridge.mqtt.aws.password = public`
`bridge.mqtt.aws.forwards = topic/emqxtoaws`
`bridge.mqtt.aws.forward_mountpoint = bridge/aws/${node}/`
`bridge.mqtt.aws.ssl = on`
`bridge.mqtt.aws.cacertfile = /opt/emqx/etc/certs/SFSRootCAG2.pem`
`bridge.mqtt.aws.certfile = /opt/emqx/etc/certs/b1a21db19c-certificate.pem.crt`
`bridge.mqtt.aws.keyfile = /opt/emqx/etc/certs/b1a21db19c-private.pem.key`
`bridge.mqtt.aws.ciphers = ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384`
`bridge.mqtt.aws.keepalive = 60s`
`bridge.mqtt.aws.tls_versions = tlsv1.2,tlsv1.1,tlsv1`
`bridge.mqtt.aws.reconnect_interval = 30s`
`bridge.mqtt.aws.retry_interval = 20s`
`bridge.mqtt.aws.batch_size = 32`
`bridge.mqtt.aws.max_inflight_size = 32`
`bridge.mqtt.aws.queue.replayq_seg_bytes = 10MB`
`bridge.mqtt.aws.queue.max_total_size = 5GB`

**Comment by sgoveia** [comment]
@turtleDeng any thoughts on the above issue I am having? Thank you..

**Comment by turtleDeng** [comment]
Thanks for your feedback, please provide a detailed log.

**Comment by sgoveia** [comment]
Hello @turtleDeng , thanks for the response! 
[emqx.log.1.log](https://github.com/emqx/emqx-bridge-mqtt/files/4103591/emqx.log.1.log)

**Comment by turtleDeng** [comment]
Thank you for your feedback. From the log analysis, your SSL connection failed. You can check the correctness of the certificate or analyze it through Capture.
```
2020-01-19 20:24:54.474 [error]     supervisor: {local,emqx_bridge_mqtt_sup}
    errorContext: child_terminated
    reason: {{case_clause,
                 {error,
                     {{shutdown,ssl_closed},
                      {ssl_closed,
                          {sslsocket,
                              {gen_tcp,#Port<0.36>,tls_connection,undefined},
                              [<0.1819.0>,<0.1818.0>]}}},
                     #{batch_size => 32,bridge_handler => undefined,
                       connect_fun => #Fun<emqx_bridge_worker.0.90725211>,
                       connect_module => emqx_bridge_mqtt,
                       connection => undefined,
                       forwards => [<<"topic/emqxtoaws">>],
                       if_record_metrics => true,inflight => [],
                       max_inflight => 32,
                       mountpoint => <<"bridge/aws/80500263eec0@172.17.0.2/">>,
                       name => emqx_bridge_worker_aws,
                       receive_mountpoint => undefined,
                       reconnect_delay_ms => 30000,
                       replayq =>
                           #{config => mem_only,
                             in_mem => {[],[]},
                             max_total_bytes => 2000000000,
                             sizer => fun emqx_bridge_msg:estimate_size/1,
                             stats => #{bytes => 0,count => 0}},
                       start_type => manual,subscriptions => []}}},
             [{emqx_bridge_worker,idle,3,
                  [{file,
                       "/emqx_rel/_build/emqx/lib/emqx_bridge_mqtt/src/emqx_bridge_worker.erl"},
                   {line,307}]},
              {gen_statem,loop_state_callback,11,
                  [{file,"gen_statem.erl"},{line,1159}]},
              {proc_lib,init_p_do_apply,3,
                  [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,<0.1788.0>},
               {id,aws},
               {mfargs,
                   {emqx_bridge_worker,start_link,
                       [aws,
                        [{address,
                             "a3qeho93ob90uv-ats.iot.us-east-1.amazonaws.com:8883"},
                         {batch_size,32},
                         {bridge_mode,true},
                         {clean_start,true},
                         {clientid,"bridge_aws"},
                         {connect_module,emqx_bridge_mqtt},
                         {forward_mountpoint,"bridge/aws/${node}/"},
                         {forwards,["topic/emqxtoaws"]},
                         {keepalive,60},
                         {max_inflight_size,32},
                         {password,"public"},
                         {proto_ver,v4},
                         {queue,
                             #{max_total_size => 5368709120,
                               replayq_seg_bytes => 10485760}},
                         {reconnect_delay_ms,30000},
                         {retry_interval,20000},
                         {ssl,true},
                         {ssl_opts,
                             [{versions,['tlsv1.2','tlsv1.1',tlsv1]},
                              {keyfile,
                                  "/opt/emqx/etc/certs/b1a21db19c-private.pem.key"},
                              {ciphers,
                                  ["ECDHE-ECDSA-AES256-GCM-SHA384",
                                   "ECDHE-RSA-AES256-GCM-SHA384"]},
                              {certfile,
                                  "/opt/emqx/etc/certs/b1a21db19c-certificate.pem.crt"},
                              {cacertfile,
                                  "/opt/emqx/etc/certs/SFSRootCAG2.pem"}]},
                         {start_type,manual},
                         {subscriptions,[]},
                         {username,"admin"}]]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
```

**Comment by HJianBo** [comment]
Hi, @sgoveia Any updates for there? Is the question resolved?

**Comment by saumilsdk** [comment]
hi @sgoveia some of your configurations are wrong. You can't have username, password, forward_mountpoint options for AWS as those are not supported on connecting to IOT Core. Please remove those and try. I am able to connect to AWS IOT core anyway.

**Comment by wwhai** [comment]
> hi @sgoveia and @HJianBo some of your configurations are wrong. You can't have username, password, forward_mountpoint options for AWS as those are not supported on connecting to IOT Core. Please remove those and try. I am able to connect to AWS IOT core anyway.

——
Thanks for you reply ,this problem seems been resolved and we can’t  reappear  ,please re-issue if this situation appear in future.

**Comment by saqib-cielo** [comment]
Emqx as a bridge with AWS Iot broker behaving unexpectedly(getting duplicate messages burst with any Qos level), normally happen when we start publishing messages with some pace, check all config params but no luck, did anyone came across similar issue.
